import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Header } from "@/components/header/header";




const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={'poppins'}>
        <Header />
        {children}
      </body>
    </html>
  );
}
